name: espressobin
version: 20-1
summary: EspressoBin gadget
description: |
  Support files for booting EspressoBin v5.
type: gadget
base: core20
assumes: [kernel-assets]
architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

package-repositories:
  - type: apt
    ppa: snappy-dev/image

confinement: strict
grade: stable
parts:
  gadget:
    plugin: nil
    source: .
    override-build: |
      set -x
      # unconditionally set the arch-triplet since this snapcraft.yaml will 
      # always be used to produce an armhf snap
      BUILD_ARCH_TRIPLET=aarch64-linux-gnu
      # but only use the cross-compiling sources when actually cross compiling
      # as otherwise its just safer to use the build environment - it offers
      # much more flexibility.
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ] || [ -z "$SNAPCRAFT_ARCH_TRIPLET" ]; then
        OPTIONAL_ARGS="SOURCES_HOST=\"./helpers/cross-sources.list\" SOURCES_D_HOST=\"./helpers\""
      fi
      make -C $SNAPCRAFT_PART_SRC core \
        DESTDIR=${SNAPCRAFT_PART_INSTALL} \
        ARCH="$(dpkg-architecture -t $BUILD_ARCH_TRIPLET -q DEB_HOST_ARCH)" \
        ${OPTIONAL_ARGS:-}
    prime:
      - boot-assets/*
      - uboot.conf
      - boot.sel
    build-packages:
      - u-boot-tools
      - lsb-release
      - dpkg-dev
      - make
      - libgdk-pixbuf2.0-dev
      - automake
      - autoconf
      - gcc
      - otf2bdf
      - libbogl-dev
      - ttf-ubuntu-font-family
      - cpio
      - findutils
      - liblz4-tool
      - libc-dev
      - try:
          - gcc-aarch64-linux-gnu:amd64
          - libc6-dev-arm64-cross:amd64

slots: {}
