name: espressobin
version: 20-1
summary: EspressoBin gadget
description: |
  Support files for booting EspressoBin v5.
type: gadget
base: core20
assumes: [kernel-assets]
architectures:
  - build-on: 
      - amd64
    run-on: arm64

package-repositories:
  - type: apt
    ppa: snappy-dev/image

confinement: strict
grade: stable

parts:
  u-boot:
    plugin: make
    source: https://github.com/u-boot/u-boot.git
    source-type: git
    source-branch: v2022.01
    source-depth: 1
    override-build: |
      make ARCH=arm mvebu_espressobin-88f3720_defconfig 
      make ARCH=arm CROSS_COMPILE=aarch64-linux-gnu- -j $(nproc)
      cp ${SNAPCRAFT_PART_BUILD}/u-boot.bin ${SNAPCRAFT_PART_INSTALL}/
      tools/mkenvimage -r -s 4096 -o ${SNAPCRAFT_PART_INSTALL}/boot.sel - < /dev/null
      touch ${SNAPCRAFT_PART_INSTALL}/uboot.conf
    build-packages:
      - libpython2.7-dev
      - bc
    prime:
        - boot.sel
        - uboot.conf
  boot-scr:
    plugin: nil
    source: .
    override-build: |
      mkimage -T script -C none -n 'Boot Script' -d boot.scr.in ${SNAPCRAFT_PART_INSTALL}/boot.scr
    build-packages:
      - sed
      - u-boot-tools
  mvddr:
    plugin: nil
    source: https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell.git
    source-type: git
    source-branch: mv_ddr-armada-18.12
    source-depth: 1
    override-build: |
      echo This package will be built by atf
      cp -r ${SNAPCRAFT_PART_SRC}/* ${SNAPCRAFT_PART_BUILD}/
  a3700-utils:
    plugin: nil
    source: https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell.git
    source-type: git
    source-branch: A3700_utils-armada-18.12
    source-depth: 1
    override-build: |
      echo This package will be built by atf
      cp -r ${SNAPCRAFT_PART_SRC}/* ${SNAPCRAFT_PART_BUILD}/
  atf:
    after: 
      - a3700-utils
      - mvddr
      - u-boot
    plugin: nil
    source: https://github.com/MarvellEmbeddedProcessors/atf-marvell.git
    source-type: git
    source-branch: atf-v1.5-armada-18.12
    source-depth: 1 
    # See http://wiki.espressobin.net/tiki-index.php?page=Build+From+Source+-+Bootloader#Build_examples for more info
    override-build: | 
      make DEBUG=1 USE_COHERENT_MEM=0 LOG_LEVEL=20 SECURE=0 \
        CLOCKSPRESET=CPU_1000_DDR_800 DDR_TOPOLOGY=2 \
        BOOTDEV=SPINOR PARTNUM=0 CROSS_COMPILE=aarch64-linux-gnu- \
        WTP=${SNAPCRAFT_PART_SRC}/../../a3700-utils/build \
        MV_DDR_PATH=${SNAPCRAFT_PART_SRC}/../../mvddr/build \
        PLAT=a3700 BL33=${SNAPCRAFT_PART_SRC}/../../u-boot/install/u-boot.bin all fip
      cp ${SNAPCRAFT_PART_BUILD}/build/a3700/debug/{flash-image.bin,uart-images.tgz} ${SNAPCRAFT_PART_INSTALL}/
    build-packages:
      # This packages builds a ARM binary for the onboard controller (Cortex M3)
      - gcc-arm-linux-gnueabi
      

slots: {}

build-packages:
  - build-essential
  - on amd64:
    - gcc-aarch64-linux-gnu
  - else:
    - gcc